#define KEY_CHCONDUCT SDLK_LCTRL
#define KEY_CHCONDUCT_LEFT SDLK_LEFT
#define KEY_CHCONDUCT_RIGHT SDLK_RIGHT

#define KEY_MENU SDLK_ESCAPE
#define KEY_MENU_UP SDLK_UP
#define KEY_MENU_DOWN SDLK_DOWN
#define KEY_MENU_ENTER SDLK_RETURN
#define KEY_MENU_QUIT SDLK_ESCAPE

#define KEY_CHAR_ACTION SDLK_SPACE
#define KEY_CHAR_ACTION_2 SDLK_w
#define KEY_CHAR_FORWARD SDLK_UP
#define KEY_CHAR_BACKWARD SDLK_DOWN
#define KEY_CHAR_LEFT SDLK_LEFT
#define KEY_CHAR_RIGHT SDLK_RIGHT
#define KEY_CHAR_USEWEAPON SDLK_LALT

#define KEY_CHAR_ATTACK_RPUNCH SDLK_RIGHT
#define KEY_CHAR_ATTACK_LPUNCH SDLK_LEFT
#define KEY_CHAR_ATTACK_KICK SDLK_UP

#define KEY_INVENT_UP SDLK_UP
#define KEY_INVENT_DOWN SDLK_DOWN
#define KEY_INVENT_LEFT SDLK_LEFT
#define KEY_INVENT_RIGHT SDLK_RIGHT
#define KEY_INVENT_QUIT SDLK_ESCAPE
#define KEY_INVENT_SHOW SDLK_SPACE
#define KEY_INVENT_SELECT SDLK_RETURN

#define KEY_ACTION_PROTOPACK SDLK_j
#define KEY_ACTION_HOLOMAP SDLK_h

#define KEY_PAUSE SDLK_p
#define KEY_INVENTORY SDLK_LSHIFT
#define KEY_RECENTER SDLK_RETURN
#define KEY_CONTTEXT SDLK_RETURN
#define KEY_SKIP SDLK_ESCAPE

